# The right place for all your configuration values.
data-sources:
    census: https://www.zensus2011.de/SharedDocs/Downloads/DE/Pressemitteilung/DemografischeGrunddaten/csv_Bevoelkerung.zip?__blob=publicationFile&v=2
push-directory: ~/Library/CloudStorage/OneDrive-ETHZurich/heat-mobility-preferences/results/
co2-share:
    transport: 21 # UBA 2023
    heat: 12 # UBA 2023
    tolerance: 3 # percentage-points
confidence-level: 0.95
attribute-order:
    - Timing
    - Purchase
    - Use
    - Support
level-order:
    heat:
        - '2030'
        - '2035'
        - '2040'
        - '2045'
        - '2050'
        - 'No purchase instrument'
        - 'Purchase tax (10%)'
        - 'Purchase tax (20%)'
        - 'Purchase ban (2025)'
        - 'Purchase ban (2030)'
        - 'No use instrument'
        - 'Tax on fossil fuels (0.2 €/l)'
        - 'Tax on fossil fuels (0.5 €/l)'
        - 'Replacement (> 15 years)'
        - 'Replacement (> 30 years)'
        - 'No supporting instrument'
        - 'Subsidies for alternatives'
        - 'Trade in bonus'
        - 'State-supported measures'
        - 'Preferential loan'
    transport:
        - '2030'
        - '2035'
        - '2040'
        - '2045'
        - '2050'
        - 'No purchase instrument'
        - 'Purchase tax (10%)'
        - 'Purchase tax (20%)'
        - 'Purchase ban (2025)'
        - 'Purchase ban (2030)'
        - 'No use instrument'
        - 'Tax on fossil fuels (0.2 €/l)'
        - 'Tax on fossil fuels (0.5 €/l)'
        - 'Weekday ban in city centers'
        - 'Daily ban in city centers'
        - 'No supporting instrument'
        - 'Subsidies for alternatives'
        - 'Trade in bonus'
        - 'State-supported measures'
        - 'Preferential loan'
subgroups:
    cceval_cat:
        name: Climate concern
        level-order: ['Low', 'Medium', 'High']
    relevance_cat:
        name: Assumed sector emission share
        level-order: ['Too low', 'Correct', 'Too high']
    First:
        name: Sector shown first
        level-order: ['Transport', 'Heating']
    choiceNum:
        name: Choice task per respondent
        level-order: [1, 2, 3, 4, 5]
    packNum:
        name: Display side
        level-order: ["Left", "Right"]
    speeders:
        name: Respondents
        level-order: ["All", "Without speeders"]
    concern_and_understanding:
        name: Climate concern and problem understanding
        level-order: ["High/low", "High/good", "Medium/low", "Medium/good", "Low/low", "Low/good"]
