# The right place for all your configuration values.
co2-share:
    transport: 25 # TODO double-check
    heat: 15 # TODO double-check
    tolerance: 3 # percentage-points
subgroups:
    cceval_cat:
        name: Climate concern
        level-order: ['Low', 'Medium', 'High']
    relevance_cat:
        name: Assumed sector emission share
        level-order: ['Too low', 'Correct', 'Too high']
