# The right place for all your configuration values.
co2-share:
    transport: 25 # TODO double-check
    heat: 15 # TODO double-check
    tolerance: 3 # percentage-points
confidence-level: 0.95
attribute-order:
    - Timing
    - Purchase
    - Use
    - Support
level-order:
    heat:
        - '2030'
        - '2035'
        - '2040'
        - '2045'
        - '2050'
        - 'No purchase instrument'
        - 'Purchase tax (10%)'
        - 'Purchase tax (20%)'
        - 'Purchase ban (2025)'
        - 'Purchase ban (2030)'
        - 'No use instrument'
        - 'Tax on fossil fuels (20 ct/l)'
        - 'Tax on fossil fuels (50 ct/l)'
        - 'Replacement (> 15 years)'
        - 'Replacement (> 30 years)'
        - 'No supporting instrument'
        - 'Subsidies for alternatives'
        - 'Trade in bonus'
        - 'State-supported measures'
        - 'Preferential loan'
    transport:
        - '2030'
        - '2035'
        - '2040'
        - '2045'
        - '2050'
        - 'No purchase instrument'
        - 'Purchase tax (10%)'
        - 'Purchase tax (20%)'
        - 'Purchase ban (2025)'
        - 'Purchase ban (2030)'
        - 'No use instrument'
        - 'Tax on fossil fuels (20 ct/l)'
        - 'Tax on fossil fuels (50 ct/l)'
        - 'Weekday ban in city centers'
        - 'Daily ban in city centers'
        - 'No supporting instrument'
        - 'Subsidies for alternatives'
        - 'Trade in bonus'
        - 'State-supported measures'
        - 'Preferential loan'
subgroups:
    cceval_cat:
        name: Climate concern
        level-order: ['Low', 'Medium', 'High']
    relevance_cat:
        name: Assumed sector emission share
        level-order: ['Too low', 'Correct', 'Too high']
    First:
        name: Sector shown first
        level-order: ['Transport', 'Heating']
