name: default
channels:
    - conda-forge
dependencies:
    - python=3.10
    - numpy=1.22.3
    - pandas=1.4.1
    - matplotlib=3.5.1
    - seaborn=0.11.2
    - altair=4.2.0
    - altair_saver=0.5.0
    - vega-cli=5.17.0
    - vega-lite-cli=4.17.0
    - seaborn=0.11.2
